site_name: DD Training
site_author: "Mia"
site_description: Training guide for Dunkin Donuts
site_url: https://46620.moe/dd
theme:
  name: material
  palette:
    scheme: slate
nav:
    - Home page: 'index.md'
    - Drinks:
        - Coffee:
            - 'Iced/Hot Coffee': 'drinks/coffee/regular.md'
#            - 'Mixology': 'drinks/coffee/mixology.md'
#            - 'Hot Chocolate': 'drinks/coffee/hotcoco.md'
#            - 'Seasonals': ''
#        - '"Teas"':
#            - 'Iced/Hot Tea': ''
#            - 'Refreshers': ''
#            - 'Matcha/Chai': ''
        - Espresso:
            - 'Americano': 'drinks/espresso/americano.md'
            - 'Lattee': 'drinks/espresso/latte.md'
            - 'Signature Lattee': 'drinks/espresso/signature-lattes.md'
#            - 'Cappuccino': 'drinks/espresso/'
#            - 'Macchiato': 'drinks/espresso/'
#        - Frozen/Oasis:
#            - 'Frozen Coffee': ''
#            - 'Frozen Chocolate': ''
#            - 'Frozen Matcha': ''
#            - 'Coolatta': ''
#            - 'Energy Punch': ''
        - Test Kitchen:
            - 'Mocha Whipped Coffee': 'drinks/test-kitchen/mocha-whipped-coffee.md'
#    - Sandwich Station:
#        - 'Sandwiches': ''
#        - 'Snacking': ''
    - Chores:
        - Cleaning:
            - 'Donut case': 'chores/cleaning/donut_case.md'
            - 'Taking out trash': 'chores/cleaning/trash.md'
            - 'Espresso machine': 'chores/cleaning/espresso.md'
            - 'Coffee Pots': 'chores/cleaning/coffee.md'
            - 'Sandwich station': 'chores/cleaning/sandwich.md'
            - 'Coolatta machine': 'chores/cleaning/coolatta.md'
            - 'Travel Path': 'chores/cleaning/travel_path.md'
        - Everything else:
            - 'Redbook': 'chores/misc/redbook.md'
    - Misc:
        - 'Fixes': 'misc/fixes.md'

markdown_extensions:
    - admonition
    - pymdownx.details
    - fontawesome_markdown
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true